semantics/urls.py
from django.urls import path
from .views import denotation, weakest_precondition, index
from django.conf import settings
from django.conf.urls.static import static

app_name = 'semantics'
urlpatterns = [
    path('', index, name='index'),
    path('denotation/', denotation, name='denotation'),
    path('weakest_precondition/', weakest_precondition, name='weakest_precondition'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('semantics.urls', namespace='semantics')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

semantics/models.py
from django.db import models

# Create your models here.

semantics/forms.py
from django import forms


class DenotationalForm(forms.Form):
    code = forms.CharField()


class WeakestPreconditionForm(forms.Form):
    code = forms.CharField()
    number = forms.IntegerField()

semantics/views.py
from django.shortcuts import render
from .translators.denotation import translate as denotation_translate
from .translators.weakest_precondition import translate as weakest_precondition_translate
from .forms import DenotationalForm, WeakestPreconditionForm


def index(request):
    return render(request, 'semantics/index.html')


def denotation(request):
    data = {}
    if request.method == 'POST':
        form = DenotationalForm(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            data['code'] = code
            with open('log.txt', 'w') as file:
                file.write(code)
            try:
                steps = denotation_translate(code)
            except Exception as e:
                data['is_mistake'] = True
                data['mistake'] = str(e)
            else:
                data['is_mistake'] = False
                data['steps'] = steps
    else:
        form = DenotationalForm()

    return render(request, 'semantics/denotation.html', {'data': data})


def weakest_precondition(request):
    data = {}
    if request.method == 'POST':
        form = WeakestPreconditionForm(request.POST)

        if form.is_valid():
            code = form.cleaned_data['code']
            data['code'] = code
            number = form.cleaned_data['number']
            data['number'] = number
            with open('log.txt', 'w') as file:
                file.write(code)
            try:
                steps = weakest_precondition_translate(code, number)
            except Exception as e:
                data['is_mistake'] = True
                data['mistake'] = str(e)
            else:
                data['is_mistake'] = False
                data['steps'] = steps
    else:
        form = WeakestPreconditionForm()

    return render(request, 'semantics/weakest_precondition.html', {'data': data})

semantics/templates/semantics/denotation.html
{% extends 'semantics/main.html' %}

{% block title %}
<title>Denotational semantics</title>
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <form action="{% url 'semantics:denotation' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="code_area">Your code here</label>
          <textarea style="white-space: pre-wrap;" id="code_area" class="form-control" name="code" cols="80" rows="10" type="text">{{data.code}}</textarea>
        </div>
        <button class="btn btn-primary" id="apply_btn" type="submit">Apply denotational semantics</button>
      </form>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <button class="btn btn-primary" id="next_step_btn">Next step</button>
    </div>
    <div class="col-sm-8">
        {% if data.is_mistake == True %}
        <p>There is a mistake in: {{data.mistake}}</p>
        {% else %}
          {% for step in data.steps %}
          {% if forloop.counter0 == 0 %}
          <div id="step_{{forloop.counter0}}">
          {% else %}
            <div style="display:none;" id="step_{{forloop.counter0}}">
          {% endif %}
              {{step}}
              <hr>
            </div>
          {% endfor %}
        {% endif %}
    </div>
    <div class="col-sm-2"></div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  let counter = 1
  function update_counter(a){
    document.getElementById("step_"+counter).style.display = "block"
    counter += 1
  }
  document.getElementById("next_step_btn").addEventListener("click", update_counter)
  document.getElementById("apply_btn").addEventListener("click", update_counter)
</script>
{% endblock %}

semantics/templates/semantics/index.html
{% extends 'semantics/main.html' %}

{% block title %}
<title>Main page</title>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <p>Here some text</p>
      </div>
    </div>
  </div>
{% endblock %}

semantics/templates/semantics/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load staticfiles %}
  {% block title %}
  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
</head>
<body>
  <div class="jumbotron text-center" style = "margin-bottom:0">
    <h1>Fun with formal semantics</h1>
  </div>
  {% url 'semantics:index' as url_home %}
  {% url 'semantics:denotation' as url_denotation %}
  {% url 'semantics:weakest_precondition' as url_weakest_precondition %}
 <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
   <a class="navbar-brand" href="{{url_home}}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{url_denotation}}">Denotational semantics</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_weakest_precondition}}">Weakest precondition</a>
        </li>
      </ul>
    </div>
  </nav>
  {% block content %}
  {% endblock %}
</body>
  {% block scripts %}
  {% endblock %}
</html>

semantics/templates/semantics/weakest_precondition.html
{% extends 'semantics/main.html' %}

{% block title %}
<title>Weakest precondition semantics</title>
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <form action="{% url 'semantics:weakest_precondition' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="code_area">Your code here</label>
          <textarea style="white-space: pre-wrap;" id="code_area" class="form-control" name="code" cols="80" rows="10" type="text">{{data.code}}</textarea>
        </div>
        <div class="form-group">
          <label for="number_area">Your number here</label>
          <textarea style="white-space: pre-wrap;" id="number_area" class="form-control" name="number" cols="10" rows="1" type="text">{{data.number}}</textarea>
        </div>
        <button class="btn btn-primary" id="apply_btn" type="submit">Apply weakest precondition</button>
      </form>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <div class="row">
    <div class="col-sm-2">
      <button class="btn btn-primary" id="next_step_btn">Next step</button>
    </div>
    <div class="col-sm-8">
        {% if data.is_mistake == True %}
        <p>There is a mistake in: {{data.mistake}}</p>
        {% else %}
          {% for step in data.steps %}
          {% if forloop.counter0 == 0 %}
          <div id="step_{{forloop.counter0}}">
          {% else %}
            <div style="display:none;" id="step_{{forloop.counter0}}">
          {% endif %}
              {{step}}
              <hr>
            </div>
          {% endfor %}
        {% endif %}
    </div>
    <div class="col-sm-2"></div>
  </div>
</div>
{% endblock %}

{% block scripts %}
<script>
  let counter = 1
  function update_counter(a){
    document.getElementById("step_"+counter).style.display = "block"
    counter += 1
  }
  document.getElementById("next_step_btn").addEventListener("click", update_counter)
  document.getElementById("apply_btn").addEventListener("click", update_counter)
</script>
{% endblock %}